services:
  web:
    container_name: ft_transcendence
    build:
      context: .
      dockerfile: Dockerfile
    image: ft_transcendence
    ports:
      - "3000:3000"
    command: npm run dev
    restart: unless-stopped